// Command codepagegen writes codepage_tables.go from the pinned Windows
// best-fit files in .external/codepages (make codepages). It accepts only
// complete single-byte MBTABLEs whose ASCII half is the identity.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/mgilbir/gowemf/internal/codepage"
	"github.com/mgilbir/gowemf/internal/corpus"
)

func main() {
	out := flag.String("o", "codepage_tables.go", "output file")
	flag.Parse()
	src, err := generate(filepath.Join(".external", "codepages"))
	if err == nil {
		err = os.WriteFile(*out, src, 0644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(dir string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/codepagegen from the Windows best-fit code page\n")
	b.WriteString("// files named by MS-UCODEREF 2.2.2 (Unicode License V3, see THIRD_PARTY_NOTICES.md).\n")
	b.WriteString("// DO NOT EDIT.\n\npackage gowemf\n\n")
	b.WriteString("// codePageHigh maps bytes 0x80-0xFF of each single-byte ANSI code page to\n")
	b.WriteString("// UTF-16. Bytes 0x00-0x7F are the identity in every listed code page.\n")
	b.WriteString("var codePageHigh = map[uint16]*[128]uint16{\n")
	for _, f := range corpus.CodePages {
		data, err := os.ReadFile(filepath.Join(dir, f.Path))
		if err != nil {
			return nil, err
		}
		t, err := codepage.Parse(data)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", f.Path, err)
		}
		fmt.Fprintf(&b, "\t%d: {", t.CodePage)
		for i, v := range t.Bytes[128:] {
			if i%8 == 0 {
				b.WriteString("\n\t\t")
			}
			fmt.Fprintf(&b, "0x%04x, ", v)
		}
		b.WriteString("\n\t},\n")
		if !strings.HasSuffix(f.Path, fmt.Sprintf("%d.txt", t.CodePage)) {
			return nil, fmt.Errorf("%s declares code page %d", f.Path, t.CodePage)
		}
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
