// Command bidigen writes internal/bidi/tables.go from the pinned Unicode
// Character Database files in .external/unicode (make bidi): the Bidi_Class of
// every code point, with the @missing defaults of DerivedBidiClass.txt, and
// the Bidi_Paired_Bracket pairs of BidiBrackets.txt.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/mgilbir/gowemf/internal/bidi"
)

func main() {
	out := flag.String("o", filepath.Join("internal", "bidi", "tables.go"), "output file")
	flag.Parse()
	src, err := generate(filepath.Join(".external", "unicode"))
	if err == nil {
		err = os.WriteFile(*out, src, 0644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// longNames maps the Bidi_Class long value aliases used by @missing lines.
var longNames = map[string]string{
	"Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL", "European_Number": "EN",
	"European_Separator": "ES", "European_Terminator": "ET", "Arabic_Number": "AN",
	"Common_Separator": "CS", "Nonspacing_Mark": "NSM", "Boundary_Neutral": "BN",
	"Paragraph_Separator": "B", "Segment_Separator": "S", "White_Space": "WS", "Other_Neutral": "ON",
	"Left_To_Right_Embedding": "LRE", "Left_To_Right_Override": "LRO", "Right_To_Left_Embedding": "RLE",
	"Right_To_Left_Override": "RLO", "Pop_Directional_Format": "PDF", "Left_To_Right_Isolate": "LRI",
	"Right_To_Left_Isolate": "RLI", "First_Strong_Isolate": "FSI", "Pop_Directional_Isolate": "PDI",
}

func codeRange(s string) (lo, hi uint32, err error) {
	a, b, ok := strings.Cut(strings.TrimSpace(s), "..")
	if !ok {
		b = a
	}
	x, err1 := strconv.ParseUint(a, 16, 32)
	y, err2 := strconv.ParseUint(b, 16, 32)
	if err1 != nil || err2 != nil || x > y || y > 0x10ffff {
		return 0, 0, fmt.Errorf("code point range %q", s)
	}
	return uint32(x), uint32(y), nil
}

func generate(dir string) ([]byte, error) {
	classes := make([]bidi.Class, 0x110000)
	explicit := make([]bool, 0x110000)
	data, err := os.ReadFile(filepath.Join(dir, "extracted", "DerivedBidiClass.txt"))
	if err != nil {
		return nil, err
	}
	s := bufio.NewScanner(bytes.NewReader(data))
	for s.Scan() {
		line := s.Text()
		if rest, ok := strings.CutPrefix(line, "# @missing:"); ok {
			// Defaults apply in file order, each overriding the previous.
			r, name, ok := strings.Cut(rest, ";")
			short, known := longNames[strings.TrimSpace(name)]
			c, valid := bidi.ParseClass(short)
			if !ok || !known || !valid {
				return nil, fmt.Errorf("@missing line %q", line)
			}
			lo, hi, err := codeRange(r)
			if err != nil {
				return nil, err
			}
			for cp := lo; cp <= hi; cp++ {
				if !explicit[cp] {
					classes[cp] = c
				}
			}
			continue
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		if strings.TrimSpace(line) == "" {
			continue
		}
		r, name, ok := strings.Cut(line, ";")
		c, valid := bidi.ParseClass(strings.TrimSpace(name))
		if !ok || !valid {
			return nil, fmt.Errorf("Bidi_Class line %q", line)
		}
		lo, hi, err := codeRange(r)
		if err != nil {
			return nil, err
		}
		for cp := lo; cp <= hi; cp++ {
			if explicit[cp] {
				return nil, fmt.Errorf("U+%04X listed twice", cp)
			}
			explicit[cp], classes[cp] = true, c
		}
	}
	if err := s.Err(); err != nil {
		return nil, err
	}

	type pair struct{ open, close uint32 }
	var pairs []pair
	closers := map[uint32]uint32{}
	data, err = os.ReadFile(filepath.Join(dir, "BidiBrackets.txt"))
	if err != nil {
		return nil, err
	}
	s = bufio.NewScanner(bytes.NewReader(data))
	for s.Scan() {
		line := s.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		if strings.TrimSpace(line) == "" {
			continue
		}
		f := strings.Split(line, ";")
		if len(f) != 3 {
			return nil, fmt.Errorf("BidiBrackets line %q", line)
		}
		cp, _, err1 := codeRange(f[0])
		other, _, err2 := codeRange(f[1])
		if err1 != nil || err2 != nil || classes[cp] != bidi.ON || classes[other] != bidi.ON {
			return nil, fmt.Errorf("BidiBrackets line %q", line)
		}
		switch strings.TrimSpace(f[2]) {
		case "o":
			pairs = append(pairs, pair{cp, other})
		case "c":
			closers[cp] = other
		default:
			return nil, fmt.Errorf("BidiBrackets type %q", line)
		}
	}
	if err := s.Err(); err != nil {
		return nil, err
	}
	for _, p := range pairs {
		if closers[p.close] != p.open {
			return nil, fmt.Errorf("U+%04X and U+%04X are not mutual brackets", p.open, p.close)
		}
		delete(closers, p.close)
	}
	if len(closers) != 0 || len(pairs) == 0 {
		return nil, fmt.Errorf("unpaired closing brackets")
	}
	for i := 1; i < len(pairs); i++ {
		if pairs[i].open <= pairs[i-1].open {
			return nil, fmt.Errorf("brackets out of order")
		}
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/bidigen from the Unicode Character Database\n")
	b.WriteString("// 18.0.0 (Unicode License V3, see THIRD_PARTY_NOTICES.md). DO NOT EDIT.\n\npackage bidi\n\n")
	b.WriteString("// UnicodeVersion is the Unicode Character Database the tables come from.\n")
	b.WriteString("const UnicodeVersion = \"18.0.0\"\n\n")
	b.WriteString("// classStarts holds the first code point of each run of equal Bidi_Class\n")
	b.WriteString("// values; classValues holds the class of each run, which extends to the\n// next start.\n")
	var starts []uint32
	var values []bidi.Class
	for cp := uint32(0); cp < 0x110000; cp++ {
		if cp == 0 || classes[cp] != classes[cp-1] {
			starts = append(starts, cp)
			values = append(values, classes[cp])
		}
	}
	b.WriteString("var classStarts = [...]uint32{")
	for i, v := range starts {
		if i%8 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "0x%05x, ", v)
	}
	b.WriteString("\n}\n\nvar classValues = [...]Class{")
	for i, v := range values {
		if i%12 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "%s, ", v)
	}
	b.WriteString("\n}\n\n// bracketPairs lists each opening paired bracket with its closing bracket\n// (Bidi_Paired_Bracket), ordered by the opening bracket.\n")
	b.WriteString("var bracketPairs = [...][2]rune{")
	for i, p := range pairs {
		if i%4 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "{0x%04x, 0x%04x}, ", p.open, p.close)
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].close < pairs[j].close })
	b.WriteString("\n}\n\n// closingBrackets lists each closing paired bracket with its opening\n// bracket, ordered by the closing bracket.\n")
	b.WriteString("var closingBrackets = [...][2]rune{")
	for i, p := range pairs {
		if i%4 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "{0x%04x, 0x%04x}, ", p.close, p.open)
	}
	b.WriteString("\n}\n")
	return format.Source(b.Bytes())
}
